### ISSUE TITLE
Support all query filters from Firestore

### ISSUE THREAD

**Issue by fbjorn** [digitalliving/firedantic#2]
```python
    @classmethod
    def find(cls: Type[TModel], filter_: dict) -> List[TModel]:
        """Returns a list of models from the database based on a filter.
        :param filter_: The filter criteria.
        :return: List of found models.
        """
        coll = cls._get_col_ref()

        query = coll

        for key, value in filter_.items():
            query = query.where(key, "==", value)
```

Currently we assume that filters can only contain equality checks, cause we're composing query as `.where(key, "==", value)`.

Need to support other filters like `>=` or `in`.

The list of supported operations can be found [in firestore docs](https://googleapis.dev/python/firestore/latest/query.html#google.cloud.firestore_v1.query.Query.where)

**Comment by lietu** [comment]
Solved by #11
